<?php

namespace App\Listeners;

use App\Events\ViolationRecorded;
use App\Notifications\NewViolationNotification;
use App\Services\TelegramService;
use App\Support\ViolationMessageBuilder;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Facades\Notification;
use Throwable;

/**
 * Listens for the ViolationRecorded event and sends notifications
 * through various channels like email and Telegram.
 *
 * This listener is queued to ensure that sending notifications does not
 * slow down the user's web request.
 */
class SendViolationNotifications implements ShouldQueue
{
    use InteractsWithQueue;

    /**
     * The service responsible for sending messages via Telegram.
     */
    protected TelegramService $telegramService;

    /**
     * Create the event listener.
     *
     * Laravel's service container will automatically inject an instance
     * of the TelegramService here (Dependency Injection).
     */
    public function __construct(TelegramService $telegramService)
    {
        $this->telegramService = $telegramService;
    }

    /**
     * Handle the event.
     *
     * This is the main method that gets executed when the
     * ViolationRecorded event is fired.
     */
    public function handle(ViolationRecorded $event): void
    {
        // 1. Send an email notification if an email is provided.
        if (isset($event->driverInfo['email'])) {
            Notification::route('mail', $event->driverInfo['email'])
                ->notify(new NewViolationNotification($event->violation, $event->driverInfo));
        }

        // 2. Send a Telegram notification.
        // The message content is generated by the builder to keep logic centralized.
        $message = ViolationMessageBuilder::buildTelegramMessage($event->violation, $event->driverInfo);

        $this->telegramService->sendMessage($message);
    }

    /**
     * Handle a job failure.
     *
     * If sending notifications fails and the job is moved to the failed_jobs table,
     * this method will be called. You can add logging or alerts here.
     */
    public function failed(ViolationRecorded $event, Throwable $exception): void
    {
        // Log the error for debugging purposes.
        \Log::error('Failed to send violation notification for plate: '.$event->violation->plate_num, [
            'error' => $exception->getMessage(),
        ]);
    }
}
