# تعطيل ضغط الاستجابة
SetEnv no-gzip 1

# زيادة مهلة الاتصال
Timeout 3600
ProxyTimeout 3600

<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted

        # تعطيل الكاش + تفعيل SSE headers
        Header set Cache-Control "no-cache"
        Header set Connection "keep-alive"
        Header set Content-Type "text/event-stream"
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
