import type { Metadata } from "next";
import "../styles/main.scss";
import Providers from "@/context/Providers";

export const metadata: Metadata = {
  title: "Limi Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
