import type { Metadata } from "next";
import "../styles/main.scss";
import Providers from "@/context/Providers";

export const metadata: Metadata = {
  title: "Traffic Violation Detection",
  description: "Generated by Nour AL-Assad",
  icons: {
    icon: "/logo1.ico",
    shortcut: "/logo1.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
