import "../styles/main.scss";
import Providers from "@/context/Providers";

export const metadata = {
  title: "Traffic Violation Detection",
  description: "Generated by Nour AL-Assad",
  icons: {
    icon: "/Gold.ico",
    shortcut: "/Gold.ico",
  },
  other: {
    "font-cairo":
      "https://fonts.googleapis.com/css2?family=Cairo:wght@400;500;600;700&display=swap",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" className="dark">
      <body className="font-cairo">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
