<?php

namespace Database\Factories;

use App\Models\ViolationType;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\ViolationType>
 */
class ViolationTypeFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = ViolationType::class;

    /**
     * Define the model's default state.
     *
     * Defines the structure of a fake "Violation Type".
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // A predefined array of realistic violation types.
        static $types = [
            ['type_name' => 'اكتشاف عدم وضع حزام الأمان', 'key' => 'no_seatbelt', 'fine_amount' => 20000], // Stored in Halalas (200.00 SAR)
            ['type_name' => 'اكتشاف استعمال الهاتف أثناء القيادة', 'key' => 'phone_usage', 'fine_amount' => 30000], // 300.00 SAR
            ['type_name' => 'اكتشاف تجاوز الإشارة الحمراء', 'key' => 'red_light', 'fine_amount' => 40000], // 400.00 SAR
            ['type_name' => 'اكتشاف القيادة عكس السير', 'key' => 'wrong_way', 'fine_amount' => 50000], // 500.00 SAR
            ['type_name' => 'اكتشاف غياب لوحة المركبة', 'key' => 'no_plate', 'fine_amount' => 15000], // 150.00 SAR
        ];

        // Using faker->unique() ensures that we don't try to insert the same 'key' twice,
        // which would cause a database error. It will throw an exception if it runs out of unique elements.
        $type = $this->faker->unique()->randomElement($types);

        return [
            // 'v_type_id' is automatically generated by the HasUuids trait in the ViolationType model.
            'type_name' => $type['type_name'],
            'key' => $type['key'],
            'fine_amount' => $type['fine_amount'],
        ];
    }
}
