<?php

namespace Database\Factories;

use App\Models\Camera;
use App\Models\Violation;
use App\Models\ViolationType;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Violation>
 */
class ViolationFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Violation::class;

    /**
     * Define the model's default state.
     *
     * Defines what a fake "Violation" should look like.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // Important: This assumes that you have already seeded the 'violation_types' table.
        $violationType = ViolationType::inRandomOrder()->first();

        // Note: This creates a new camera for every new violation.
        // This is fine for small tests, but for large-scale seeding,
        // it's better to create cameras first and then assign them randomly.
        $camera = Camera::factory()->create();

        return [
            // 'v_id' is automatically generated by the HasUuids trait in the Violation model.
            'v_type_id' => $violationType->v_type_id,
            'camera_id' => $camera->camera_id,
            'plate_num' => strtoupper($this->faker->bothify('???-####')),
            'timestamp' => $this->faker->dateTimeBetween('-30 days', 'now'),
        ];
    }
}
